import requests
import os
from groq import Groq
from dotenv import load_dotenv
import json

load_dotenv(dotenv_path=r"C:\Users\Harsh Sharma\Desktop\ideaforge\.env")

GITLAB_TOKEN = os.getenv("GITLAB_TOKEN")
GROQ_KEY = os.getenv("GROQ_API_KEY")
PROJECT_ID = os.getenv("GITLAB_PROJECT_ID")

def create_branch(branch_name):
    url = f"https://gitlab.com/api/v4/projects/{PROJECT_ID}/repository/branches"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    data = {"branch": branch_name, "ref": "main"}
    response = requests.post(url, headers=headers, data=data)
    return response.status_code == 201

def generate_fix_code(analysis, solutions, security):
    client = Groq(api_key=GROQ_KEY)
    chat_completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": f"""
You are a world-class software engineer.

Analysis: {analysis}
Solutions: {solutions}
Security Notes: {security}

Write a production-ready code fix.
Include the actual code changes needed.
Format as:

FILENAME: (file to change)
CODE FIX:
(actual code here)

EXPLANATION:
(why this fixes it)
"""
            }
        ]
    )
    return chat_completion.choices[0].message.content

def create_merge_request(branch_name, analysis, solutions, fix_code):
    url = f"https://gitlab.com/api/v4/projects/{PROJECT_ID}/merge_requests"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    data = {
        "source_branch": branch_name,
        "target_branch": "main",
        "title": f"fix: Auto-fix by IdeaForge AI Agent",
        "description": f"""
## 🤖 IdeaForge AI — Auto Generated Fix

### Problem Analysis
{analysis}

### Proposed Solution
{solutions}

### Code Fix
{fix_code}

---
*Generated by IdeaForge AI Agent*
        """,
        "labels": "ai-generated,bug-fix"
    }
    response = requests.post(url, headers=headers, data=data)
    return response.json()

def run_agent5(analysis, solutions, security):
    print("\n🚀 AGENT 5 — PR Generator Starting...")
    print("=" * 50)

    branch_name = "fix/ideaforge-ai-autofix"
    print(f"📌 Creating branch: {branch_name}")
    create_branch(branch_name)

    print("💻 Generating fix code...")
    fix_code = generate_fix_code(analysis, solutions, security)
    print(fix_code)

    print("\n📬 Creating Merge Request...")
    mr = create_merge_request(branch_name, analysis, solutions, fix_code)

    if mr.get('web_url'):
        print(f"✅ MR Created: {mr['web_url']}")
    else:
        print(f"MR Response: {mr}")

    print("=" * 50)
    return fix_code

if __name__ == "__main__":
    test_analysis = "Login button not working on iOS mobile devices"
    test_solutions = "Fix CSS touch events and update HTML button element"
    test_security = "Score 4/10 - needs input validation"
    run_agent5(test_analysis, test_solutions, test_security)