import requests
import os
import re
import base64
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

GITLAB_TOKEN = os.getenv("GITLAB_TOKEN")
GROQ_KEY = os.getenv("GROQ_API_KEY")
PROJECT_ID = os.getenv("GITLAB_PROJECT_ID")

def create_branch(branch_name):
    url = f"https://gitlab.com/api/v4/projects/{PROJECT_ID}/repository/branches"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    data = {"branch": branch_name, "ref": "main"}
    response = requests.post(url, headers=headers, data=data)
    return response.status_code == 201

def commit_file(branch_name, file_path, content, commit_message):
    """Commit a file to the specified branch."""
    # URL-encode the file path for the API
    encoded_path = requests.utils.quote(file_path, safe='')
    url = f"https://gitlab.com/api/v4/projects/{PROJECT_ID}/repository/files/{encoded_path}"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN, "Content-Type": "application/json"}
    
    # Check if file exists to determine create vs update
    check_response = requests.get(url, headers={"PRIVATE-TOKEN": GITLAB_TOKEN}, params={"ref": branch_name})
    
    data = {
        "branch": branch_name,
        "content": content,
        "commit_message": commit_message
    }
    
    if check_response.status_code == 200:
        # File exists, update it
        response = requests.put(url, headers=headers, json=data)
    else:
        # File doesn't exist, create it
        response = requests.post(url, headers=headers, json=data)
    
    if response.status_code in [200, 201]:
        print(f"\u2705 Committed: {file_path}")
        return True
    else:
        print(f"\u274c Commit failed for {file_path}: {response.text}")
        return False

def generate_fix_code(analysis, solutions, security):
    client = Groq(api_key=GROQ_KEY)
    chat_completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": f"""
You are a world-class software engineer.

Analysis: {analysis}
Solutions: {solutions}
Security Notes: {security}

Write a production-ready code fix.
Include the actual code changes needed.
Format as:

FILENAME: (file to change, e.g., src/auth.py)
CODE FIX:
```
(actual code here)
```

EXPLANATION:
(why this fixes it)
"""
            }
        ]
    )
    return chat_completion.choices[0].message.content

def parse_fix_code(fix_code_response):
    """Parse the AI response to extract filename and code."""
    # Extract filename
    filename_match = re.search(r'FILENAME:\s*(.+?)\n', fix_code_response)
    filename = filename_match.group(1).strip() if filename_match else "fix.py"
    
    # Extract code block
    code_match = re.search(r'```(?:\w+)?\n(.*?)```', fix_code_response, re.DOTALL)
    code = code_match.group(1).strip() if code_match else fix_code_response
    
    return filename, code

def create_merge_request(branch_name, analysis, solutions, fix_code):
    url = f"https://gitlab.com/api/v4/projects/{PROJECT_ID}/merge_requests"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    data = {
        "source_branch": branch_name,
        "target_branch": "main",
        "title": "fix: Auto-fix by IdeaForge AI Agent",
        "description": f"""
## \U0001F916 IdeaForge AI — Auto Generated Fix

### Problem Analysis
{analysis[:1000]}...

### Proposed Solution
{solutions[:1000]}...

### Code Fix
{fix_code[:2000]}...

---
*Generated by IdeaForge AI Agent*
        """,
        "labels": "ai-generated,bug-fix"
    }
    response = requests.post(url, headers=headers, data=data)
    return response.json()

def run_agent5(analysis, solutions, security):
    print("\n\U0001F680 AGENT 5 — PR Generator Starting...")
    print("=" * 50)

    branch_name = "fix/ideaforge-ai-autofix"
    print(f"\U0001F4CC Creating branch: {branch_name}")
    branch_created = create_branch(branch_name)
    
    if not branch_created:
        print("\u26A0\uFE0F Branch may already exist, continuing...")

    print("\U0001F4BB Generating fix code...")
    fix_code = generate_fix_code(analysis, solutions, security)
    print(fix_code)
    
    # Parse and commit the generated code
    print("\n\U0001F4BE Committing code to branch...")
    filename, code = parse_fix_code(fix_code)
    commit_success = commit_file(
        branch_name, 
        filename, 
        code, 
        "fix: Apply IdeaForge AI generated fix"
    )
    
    if not commit_success:
        print("\u274c Failed to commit code. MR creation aborted.")
        return fix_code

    print("\n\U0001F4EC Creating Merge Request...")
    mr = create_merge_request(branch_name, analysis, solutions, fix_code)

    if mr.get('web_url'):
        print(f"\u2705 MR Created: {mr['web_url']}")
    else:
        print(f"MR Response: {mr}")

    print("=" * 50)
    return fix_code

if __name__ == "__main__":
    test_analysis = "Login button not working on iOS mobile devices"
    test_solutions = "Fix CSS touch events and update HTML button element"
    test_security = "Score 4/10 - needs input validation"
    run_agent5(test_analysis, test_solutions, test_security)
